/**
 * QA用の一時モックデータ（50件）。
 * テスト3（好印象を大量受信した場合のUI表示）の目視確認専用。
 * 確認が終わったら app/qa-mock-likes/ ごとこのファイルも削除すること。
 */
import type { ParticipantCard } from "../lib/api";

export const mockLikeCards: ParticipantCard[] = [
  {"gender":"male","number":1,"nickname":"たろう","profile":{"age_group":"30s","occupation":"医療","height":"165-175"},"freeText":"休日はサウナに行きます。","photoUrl":null,"isSelf":false,"likedMe":true},
  {"gender":"male","number":2,"nickname":"じろう","profile":{"age_group":"40s","occupation":"公務員","height":"165-175"},"freeText":"料理が趣味で、最近は本格的なカレー作りにはまっています。スパイスから調合するタイプです。","photoUrl":null,"isSelf":false,"likedMe":true},
  {"gender":"male","number":3,"nickname":"さぶろう","profile":{"age_group":"50s+","occupation":"サービス","height":"165-175"},"freeText":null,"photoUrl":null,"isSelf":false,"likedMe":true},
  {"gender":"male","number":4,"nickname":"ゆうた","profile":{"age_group":"20s","occupation":"製造","height":"165-175"},"freeText":"犬を飼っています。","photoUrl":null,"isSelf":false,"likedMe":true},
  {"gender":"male","number":5,"nickname":"けんじ","profile":{"age_group":"30s","occupation":"販売","height":"165-175"},"freeText":null,"photoUrl":null,"isSelf":false,"likedMe":true},
  {"gender":"male","number":6,"nickname":"まさと","profile":{"age_group":"40s","occupation":"自営","height":"165-175"},"freeText":null,"photoUrl":null,"isSelf":false,"likedMe":true},
  {"gender":"male","number":7,"nickname":"しょうた","profile":{"age_group":"50s+","occupation":"無職・バイト","height":"165-175"},"freeText":null,"photoUrl":null,"isSelf":false,"likedMe":true},
  {"gender":"male","number":8,"nickname":"りく","profile":{"age_group":"20s","occupation":"その他","height":"165-175"},"freeText":"映画鑑賞が好きです。年間100本くらい観ます。","photoUrl":null,"isSelf":false,"likedMe":true},
  {"gender":"male","number":9,"nickname":"そうすけ","profile":{"age_group":"30s","occupation":"IT","height":"165-175"},"freeText":null,"photoUrl":null,"isSelf":false,"likedMe":true},
  {"gender":"male","number":10,"nickname":"だいき","profile":{"age_group":"40s","occupation":"医療","height":"165-175"},"freeText":null,"photoUrl":null,"isSelf":false,"likedMe":true},
  {"gender":"male","number":11,"nickname":"アレクサンダー・ジョンソン三世","profile":{"age_group":"50s+","occupation":"公務員","height":"165-175"},"freeText":"休日はサウナに行きます。","photoUrl":null,"isSelf":false,"likedMe":true},
  {"gender":"male","number":12,"nickname":"N","profile":{"age_group":"20s","occupation":"サービス","height":"165-175"},"freeText":"料理が趣味で、最近は本格的なカレー作りにはまっています。スパイスから調合するタイプです。","photoUrl":null,"isSelf":false,"likedMe":true},
  {"gender":"male","number":13,"nickname":"たかし","profile":{"age_group":"30s","occupation":"製造","height":"165-175"},"freeText":null,"photoUrl":null,"isSelf":false,"likedMe":true},
  {"gender":"male","number":14,"nickname":"ゆういちろう","profile":{"age_group":"40s","occupation":"販売","height":"165-175"},"freeText":"犬を飼っています。","photoUrl":null,"isSelf":false,"likedMe":true},
  {"gender":"male","number":15,"nickname":"あきら","profile":{"age_group":"50s+","occupation":"自営","height":"165-175"},"freeText":null,"photoUrl":null,"isSelf":false,"likedMe":true},
  {"gender":"male","number":16,"nickname":"はると","profile":{"age_group":"20s","occupation":"無職・バイト","height":"165-175"},"freeText":null,"photoUrl":null,"isSelf":false,"likedMe":true},
  {"gender":"male","number":17,"nickname":"こうすけ","profile":{"age_group":"30s","occupation":"その他","height":"165-175"},"freeText":null,"photoUrl":null,"isSelf":false,"likedMe":true},
  {"gender":"male","number":18,"nickname":"かずま","profile":{"age_group":"40s","occupation":"IT","height":"165-175"},"freeText":"映画鑑賞が好きです。年間100本くらい観ます。","photoUrl":null,"isSelf":false,"likedMe":true},
  {"gender":"male","number":19,"nickname":"しんじ","profile":{"age_group":"50s+","occupation":"医療","height":"165-175"},"freeText":null,"photoUrl":null,"isSelf":false,"likedMe":true},
  {"gender":"male","number":20,"nickname":"ともや","profile":{"age_group":"20s","occupation":"公務員","height":"165-175"},"freeText":null,"photoUrl":null,"isSelf":false,"likedMe":true},
  {"gender":"male","number":21,"nickname":"M21","profile":{"age_group":"30s","occupation":"サービス","height":"165-175"},"freeText":"休日はサウナに行きます。","photoUrl":null,"isSelf":false,"likedMe":true},
  {"gender":"male","number":22,"nickname":"つよし","profile":{"age_group":"40s","occupation":"製造","height":"165-175"},"freeText":"料理が趣味で、最近は本格的なカレー作りにはまっています。スパイスから調合するタイプです。","photoUrl":null,"isSelf":false,"likedMe":true},
  {"gender":"male","number":23,"nickname":"のぶひろ","profile":{"age_group":"50s+","occupation":"販売","height":"165-175"},"freeText":null,"photoUrl":null,"isSelf":false,"likedMe":true},
  {"gender":"male","number":24,"nickname":"えいた","profile":{"age_group":"20s","occupation":"自営","height":"165-175"},"freeText":"犬を飼っています。","photoUrl":null,"isSelf":false,"likedMe":true},
  {"gender":"male","number":25,"nickname":"かんた","profile":{"age_group":"30s","occupation":"無職・バイト","height":"165-175"},"freeText":null,"photoUrl":null,"isSelf":false,"likedMe":true},
  {"gender":"male","number":26,"nickname":"りょうすけ","profile":{"age_group":"40s","occupation":"その他","height":"165-175"},"freeText":null,"photoUrl":null,"isSelf":false,"likedMe":true},
  {"gender":"male","number":27,"nickname":"ひろき","profile":{"age_group":"50s+","occupation":"IT","height":"165-175"},"freeText":null,"photoUrl":null,"isSelf":false,"likedMe":true},
  {"gender":"male","number":28,"nickname":"まもる","profile":{"age_group":"20s","occupation":"医療","height":"165-175"},"freeText":"映画鑑賞が好きです。年間100本くらい観ます。","photoUrl":null,"isSelf":false,"likedMe":true},
  {"gender":"male","number":29,"nickname":"けいた","profile":{"age_group":"30s","occupation":"公務員","height":"165-175"},"freeText":null,"photoUrl":null,"isSelf":false,"likedMe":true},
  {"gender":"male","number":30,"nickname":"しゅん","profile":{"age_group":"40s","occupation":"サービス","height":"165-175"},"freeText":null,"photoUrl":null,"isSelf":false,"likedMe":true},
  {"gender":"male","number":31,"nickname":"たくと","profile":{"age_group":"50s+","occupation":"製造","height":"165-175"},"freeText":"休日はサウナに行きます。","photoUrl":null,"isSelf":false,"likedMe":true},
  {"gender":"male","number":32,"nickname":"よしお","profile":{"age_group":"20s","occupation":"販売","height":"165-175"},"freeText":"料理が趣味で、最近は本格的なカレー作りにはまっています。スパイスから調合するタイプです。","photoUrl":null,"isSelf":false,"likedMe":true},
  {"gender":"male","number":33,"nickname":"はやと","profile":{"age_group":"30s","occupation":"自営","height":"165-175"},"freeText":null,"photoUrl":null,"isSelf":false,"likedMe":true},
  {"gender":"male","number":34,"nickname":"こうた","profile":{"age_group":"40s","occupation":"無職・バイト","height":"165-175"},"freeText":"犬を飼っています。","photoUrl":null,"isSelf":false,"likedMe":true},
  {"gender":"male","number":35,"nickname":"しんいち","profile":{"age_group":"50s+","occupation":"その他","height":"165-175"},"freeText":null,"photoUrl":null,"isSelf":false,"likedMe":true},
  {"gender":"male","number":36,"nickname":"まなぶ","profile":{"age_group":"20s","occupation":"IT","height":"165-175"},"freeText":null,"photoUrl":null,"isSelf":false,"likedMe":true},
  {"gender":"male","number":37,"nickname":"じゅん","profile":{"age_group":"30s","occupation":"医療","height":"165-175"},"freeText":null,"photoUrl":null,"isSelf":false,"likedMe":true},
  {"gender":"male","number":38,"nickname":"たいが","profile":{"age_group":"40s","occupation":"公務員","height":"165-175"},"freeText":"映画鑑賞が好きです。年間100本くらい観ます。","photoUrl":null,"isSelf":false,"likedMe":true},
  {"gender":"male","number":39,"nickname":"こうじ","profile":{"age_group":"50s+","occupation":"サービス","height":"165-175"},"freeText":null,"photoUrl":null,"isSelf":false,"likedMe":true},
  {"gender":"male","number":40,"nickname":"みのる","profile":{"age_group":"20s","occupation":"製造","height":"165-175"},"freeText":null,"photoUrl":null,"isSelf":false,"likedMe":true},
  {"gender":"male","number":41,"nickname":"M41","profile":{"age_group":"30s","occupation":"販売","height":"165-175"},"freeText":"休日はサウナに行きます。","photoUrl":null,"isSelf":false,"likedMe":true},
  {"gender":"male","number":42,"nickname":"M42","profile":{"age_group":"40s","occupation":"自営","height":"165-175"},"freeText":"料理が趣味で、最近は本格的なカレー作りにはまっています。スパイスから調合するタイプです。","photoUrl":null,"isSelf":false,"likedMe":true},
  {"gender":"male","number":43,"nickname":"M43","profile":{"age_group":"50s+","occupation":"無職・バイト","height":"165-175"},"freeText":null,"photoUrl":null,"isSelf":false,"likedMe":true},
  {"gender":"male","number":44,"nickname":"M44","profile":{"age_group":"20s","occupation":"その他","height":"165-175"},"freeText":"犬を飼っています。","photoUrl":null,"isSelf":false,"likedMe":true},
  {"gender":"male","number":45,"nickname":"M45","profile":{"age_group":"30s","occupation":"IT","height":"165-175"},"freeText":null,"photoUrl":null,"isSelf":false,"likedMe":true},
  {"gender":"male","number":46,"nickname":"M46","profile":{"age_group":"40s","occupation":"医療","height":"165-175"},"freeText":null,"photoUrl":null,"isSelf":false,"likedMe":true},
  {"gender":"male","number":47,"nickname":"M47","profile":{"age_group":"50s+","occupation":"公務員","height":"165-175"},"freeText":null,"photoUrl":null,"isSelf":false,"likedMe":true},
  {"gender":"male","number":48,"nickname":"M48","profile":{"age_group":"20s","occupation":"サービス","height":"165-175"},"freeText":"映画鑑賞が好きです。年間100本くらい観ます。","photoUrl":null,"isSelf":false,"likedMe":true},
  {"gender":"male","number":49,"nickname":"M49","profile":{"age_group":"30s","occupation":"製造","height":"165-175"},"freeText":null,"photoUrl":null,"isSelf":false,"likedMe":true},
  {"gender":"male","number":50,"nickname":"M50","profile":{"age_group":"40s","occupation":"販売","height":"165-175"},"freeText":null,"photoUrl":null,"isSelf":false,"likedMe":true}
];
